# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-01 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180831_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_bet', models.IntegerField(default=0)),
                ('ou_bet', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Member')),
            ],
        ),
    ]
